### ISSUE TITLE
`_initialize_weights` not working for the whole model

### ISSUE THREAD

**Issue by ngoctnq** [ShowLo/MobileNetV3#2]
By construction, the `Sequential`, `SEModule`, and `Bottleneck` modules are not custom-initialized.

**Comment by ShowLo** [comment]
Please refer to https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=modules#torch.nn.Module.modules, it will initialize the `conv`, `linear` and `BN` in `Sequential`, `SEModule` and `Bottleneck`.

**Comment by ShowLo** [comment]
> By construction, the `Sequential`, `SEModule`, and `Bottleneck` modules are not custom-initialized.

Please refer to https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=modules#torch.nn.Module.modules, it will initialize the `conv`, `linear` and `BN` in `Sequential`, `SEModule` and `Bottleneck`.

**Comment by ngoctnq** [comment]
Well I'll be damned. Just tested and you're right, sorry for this confusing ticket.
